config/routes.rb
SmartToolsApp::Application.routes.draw do

  resources :page
   
  get 'home'=>'pages#home'

  resources :videos

  resources :contests do
    member do
      get :preview
    end
    resources :videos do
      get 'videos', on: :collection
    end
  end

  resources :contests

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

  get 'static_pages/home'
  get 'static_pages/about'

  get 'convert' => 'videos#convert'

  resources :users
  root :to => 'static_pages#home'

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  belongs_to :user
  has_many :videos, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :name, length: {maximum: 140}, presence: true, uniqueness: true
  validates :description, length: { maximum: 1000 } , presence: true
  validates :url, length: { maximum: 140 } , presence: true
  validates :startdate, presence: true, date: { after_or_equal_to: Proc.new { Date.today }, message: "must be at least #{(Date.today + 1).to_s}" }, on: :create
  validates :enddate, presence: true, date: { :after_or_equal_to => :startdate}
  def data=(incoming_file)
    self.binary_data = incoming_file.read
    self.content_type = incoming_file.content_type
    self.filename = incoming_file.original_filename
  end

  def filename=(new_filename)
    write_attribute("filename", sanitize_filename(new_filename))
  end

  private

  def sanitize_filename(filename)
    #get only the filename, not the whole path (from IE)
    just_filename = File.basename(filename)
    #replace all non-alphanumeric, underscore or periods with underscores
    just_filename.gsub(/[^\w\.\-]/, '_')
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  load_and_authorize_resource
  #load_and_authorize_resource :through => :contest
  before_action :set_contest, only: [:show, :edit, :update, :destroy]

  # GET /contests
  # GET /contests.json
  def index

      @contests = Contest.all

  end

  # GET /contests/1
  # GET /contests/1.json
  def show
  end

  # GET /contests/new
  def new
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = current_user.contests.new(contest_params) do |t|
    #@contest.user = current_user
      if contest_params[:data]
        contest_params[:data].rewind
        t.binary_data = contest_params[:data].read
        t.filename = contest_params[:data].original_filename
        t.content_type = contest_params[:data].content_type
      end
    end

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render :show, status: :created, location: @contest }
      else
        format.html { render :new }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { render :show, status: :ok, location: @contest }
      else
        format.html { render :edit }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url, notice: 'Contest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview
    @contest = Contest.find(params[:id])
    send_data(@contest.binary_data, :type => @contest.content_type, :filename => @contest.filename, :disposition => "inline")
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contest
    @contest = Contest.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contest_params
    params.require(:contest).permit(:name, :url, :startdate, :enddate, :binary_data, :content_type, :description, :user_id, :data)
  end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_form.html.erb
<div class="posted">
	<%= form_for(@contest) do |f| %>
	<% if @contest.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

		<ul>
			<% @contest.errors.full_messages.each do |message| %>
			<li>
				<%= message %>
			</li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="field">
		<%= f.label :name %>
		<br>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :url %>
		<br>
		<%= f.text_field :url %>
	</div>
	<div class="field">
		<%= f.label :startdate %>
		<br>
		<%= f.date_select :startdate %>
	</div>
	<div class="field">
		<%= f.label :enddate %>
		<br>
		<%= f.date_select :enddate %>
	</div>
	<div class="field">
		<%= f.label :data %>
		<%= f.file_field :data %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<br>
		<%= f.text_field :description %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
	<% end %>
</div>

app/views/contests/edit.html.erb
<h1>Editing contest</h1>

<%= render 'form' %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<h1 class="title">Listing contests</h1>
<%if @contests %>
<table class="posted">
	<thead>
		<tr>
			<th>Name</th>
			<th>Url</th>
			<th>Startdate</th>
			<th>Enddate</th>
			<th>Description</th>
			<th>User</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @contests.each do |contest| %>
		<tr>
			<td><%= contest.name %></td>
			<td><%= contest.url %></td>
			<td><%= contest.startdate %></td>
			<td><%= contest.enddate %></td>
			<td><%= contest.description %></td>
			<td><%= contest.user_id %></td>
			<td> <%= image_tag preview_contest_path(contest) %> </td>

			<td><%= link_to 'Show', contest %></td>

          <% if can? :edit, contest %>
			<td><%= link_to 'Edit', edit_contest_path(contest) %></td>
          <% end %>
          <% if can? :destroy, contest %>
			<td><%= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
		</tr>
		<% end %>
	</tbody>
</table>
<%end%>
<br>
<% if can? :create, Contest %>
<%= link_to 'New Contest', new_contest_path %>
<%end%>

app/views/contests/new.html.erb
<h1 class="title">New contest</h1>

<%= render 'form' %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<%= jwplayer_assets %>

<p id="notice">
	<%= notice %>
</p>

<p>
	<strong>Name:</strong>
	<%= @contest.name %>
</p>

<p>
	<strong>Url:</strong>
	<%= @contest.url %>
</p>

<p>
	<strong>Startdate:</strong>
	<%= @contest.startdate %>
</p>

<p>
	<strong>Enddate:</strong>
	<%= @contest.enddate %>
</p>

<td> <%= image_tag preview_contest_path(@contest) %> </td>

<p>
	<strong>Description:</strong>
	<%= @contest.description %>
</p>

<% if @contest.videos.any? %>
<h3>Videos(<%= @contest.videos.count %>)</h3>
<table style="height: 100%">
	<thead>
		<tr>
			<th>Name</th>
			<th>Lastname</th>
			<th>Email</th>
			<th>Message</th>
			<th>Converted</th>
			<th>Contest</th>

			<th>Player</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @contest.videos.each do |video| %>
		<tr>
			<td><%= video.name %></td>
			<td><%= video.lastname %></td>
			<td><%= video.email %></td>
			<td><%= video.message %></td>
			<td><%= video.converted %></td>
			<td><%= video.contest_id %></td>
			<td><%= video.video %></td>

			<td><%= link_to 'Show', [@contest,video] %></td>
			<td><%= link_to 'Edit', edit_contest_video_path(@contest, video) %></td>
			<td><%= link_to 'Destroy', [@contest, video], method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<% end %>
<%= link_to 'New Video', new_contest_video_path(@contest) %>
<br>

<%= link_to 'Edit', edit_contest_path(@contest) %> |
<%= link_to 'Back', contests_path %>