config/routes.rb
SmartToolsApp::Application.routes.draw do

  resources :page
   
  get 'home'=>'pages#home'

  resources :videos

  resources :contests do
    member do
      get :preview
    end
    resources :videos do
      get 'videos', on: :collection
    end
  end

  resources :contests

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

  get 'static_pages/home'
  get 'static_pages/about'

  get 'convert' => 'videos#convert'

  resources :users
  root :to => 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  has_many :contests, dependent: :destroy
  validates :username, presence: true, length: {maximum: 50}, uniqueness: true
  validates :name,  presence: true, length: { maximum: 50 }
  validates :lastname, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence:true, length: { minimum: 6 }


  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :update]
  #before_action :correct_user,   only: [:edit, :update]
  before_action :clean_error_message
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new

    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
   # user_params.permit!
    #@user = User.new(params[:user].permit!)

    if @user.save
      log_in @user
      flash[:success] = "Welcome to the SmartTools App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit!
  end

  def clean_error_message
    flash.clear()
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :username %>
	<br>
	<%= f.text_field :username %>
</div>
<div class="field">
	<%= f.label :name %>
	<br>
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :lastname %>
	<br>
	<%= f.text_field :lastname %>
</div>
<div class="field">
	<%= f.label :email %>
	<br>
	<%= f.text_field :email %>
</div>
<div class="field">
	<%= f.label :password %>
	<br>
	<%= f.password_field :password %>
</div>
<div class="field">
	<%= f.label :password_confirmation %>
	<br>
	<%= f.password_field :password_confirmation %>
</div>
<div class="actions">
	<%= f.submit "Create my account" %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class="title">New user</h1>
<div class="posted">
	<%= render 'form'%>


	<%= link_to 'Back', login_path %>
</div>

app/views/users/show.html.erb
<p id="notice">
	<%= notice %>
</p>
<p class="title">
	<strong> Welcome <%= @user.name %> <%= @user.lastname %> </strong>
</p>

<h1 class="title">Listing contests</h1>
<% if @user.contests.any? %>
<h3>Contests (<%= @user.contests.count %>)</h3>
<table class="posted">
	<thead>
		<tr>
			<th>Name</th>
			<th>Url</th>
			<th>Startdate</th>
			<th>Enddate</th>
			<th>Description</th>
			<th>User</th>
			<th>Image</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @user.contests.each do |contest| %>
		<tr>
			<td><%= contest.name %></td>
			<td><%= contest.url %></td>
			<td><%= contest.startdate %></td>
			<td><%= contest.enddate %></td>
			<td><%= contest.description %></td>
			<td><%= contest.user_id %></td>
			<td>
				<%= image_tag preview_contest_path(contest) %>
			</td>
			<td><%= link_to 'Show', contest %></td>
			<td><%= link_to 'Edit', edit_contest_path(contest) %></td>
			<td><%= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<% end %>
<br>

<%= link_to 'New Contest', new_contest_path %>