config/routes.rb
SmartToolsApp::Application.routes.draw do

  resources :page
   
  get 'home'=>'pages#home'

  resources :videos

  resources :contests do
    member do
      get :preview
    end
    resources :videos do
      get 'videos', on: :collection
    end
  end

  resources :contests

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

  get 'static_pages/home'
  get 'static_pages/about'

  get 'convert' => 'videos#convert'

  resources :users
  root :to => 'static_pages#home'

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :contest
  validates :contest_id, presence: true
  validates :name,  presence: true, length: { maximum: 50 }
  validates :lastname, presence: true, length: {maximum: 50}
  validates :message, length: { maximum: 1000 } , presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_attached_file :video,
                    :path => "public/system/:class/:id/:filename",
                    :url => "/system/:class/:id/:basename.:extension"
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  #before_action :set_video, only: [:show, :edit, :update, :destroy]
  require 'streamio-ffmpeg'
  before_filter :load_parent

  # GET /videos
  # GET /videos.json
  def index
    @videos = @contest.videos.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = @contest.videos.find(params[:id])
  end

  # GET /videos/new
  def new
    @video = @contest.videos.new
  end

  # GET /videos/1/edit
  def edit
    @video = @contest.videos.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create

    #@contest = Contest.find(params[:parent_id])

    @video =  @contest.videos.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to [@contest,@video] , notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @contest.videos.update(video_params)
        format.html { redirect_to [@contest,@video], notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = @contest.videos.find(params[:id])
    @video.destroy
    respond_to do |format|
      format.html { redirect_to [@contest,@video], notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def convert

    movie = FFMPEG::Movie.new( "public/system/videos/9/youtube.com.Muy_Buenas_Noches__Muy_Buenas_noches__Hasta_Mañana_-_YouTube.m4v")
    options = "-threads 2 -s 320x240 -r 30.00 -threads 1 -pix_fmt yuv420p -g 300 -qmin 3 -b 512k -async 50 -acodec libmp3lame -ar 11025 -ac 1 -ab 16k"
    movie.transcode("public/system/videos/9/output.flv", options)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:name, :lastname, :email, :message, :converted, :contest_id, :video)
    end
  def load_parent
    unless params[:contest_id]==nil
       @contest = Contest.find(params[:contest_id])
      end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for([@contest,@video]) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>ddd
<%= @contest.name %>bbbb
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :video %><br>
    <%= f.file_field :video %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', [@contest, @video] %> |
<%= link_to 'Back', contest_path(@contest) %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Message</th>
      <th>Converted</th>
      <th>Contest</th>
      <th>Video</th>
      <th>Player</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contest.videos.each do |video| %>
      <tr>
        <td><%= video.name %></td>
        <td><%= video.lastname %></td>
        <td><%= video.email %></td>
        <td><%= video.message %></td>
        <td><%= video.converted %></td>
        <td><%= video.contest_id %></td>
        <td><%= video.video %></td>
        <td><%= jwplayer({width: 200, height: 200, file: video.video}) %></td>
        <td><%= link_to 'Show', [@contest, video] %></td>
        <td><%= link_to 'Edit', edit_contest_video_path(@contest, video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_contest_video_path(@contest) %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', contest_path(@contest) %>

app/views/videos/show.html.erb
<%= jwplayer_assets %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @video.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @video.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @video.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @video.message %>
</p>

<p>
  <strong>Converted:</strong>
  <%= @video.converted %>
</p>

<p>
  <strong>Contest:</strong>
  <%= @video.contest_id %>
</p>

<p>
  <strong>Video:</strong>
  <%= @video.video %>
</p>

<p>
  <strong>Player:</strong>
  <%= jwplayer({file: @video.video, width: 500, height: 200}) %>
</p>


<%= link_to 'Edit', edit_contest_video_path(@contest, @video) %> |
<%= link_to 'Back', contest_path(@contest) %>