config/routes.rb
SmartToolsApp::Application.routes.draw do

  resources :page
   
  get 'home'=>'pages#home'

  resources :videos

  resources :contests do
    member do
      get :preview
    end
    resources :videos do
      get 'videos', on: :collection
    end
  end

  resources :contests

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

  get 'static_pages/home'
  get 'static_pages/about'

  get 'convert' => 'videos#convert'

  resources :users
  root :to => 'static_pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SmartToolsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Smart Tools App</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search Video">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user !=nil %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="glyphicon glyphicon-user" aria-hidden="true"></span><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to edit_user_path(current_user) do %>Profile<% end %></li>
            <li><a href="#">Other...</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to logout_path do %>Log out <span class="glyphicon glyphicon-off" aria-hidden="true"></span><% end %></li>
          </ul>
        </li>
        <% else %>
            <li><%= link_to(controller:"users", action: "new" ) do %>Sign up <span class="glyphicon glyphicon-edit" aria-hidden="true"></span><%end%></li>
            <li><%= link_to(controller:"sessions", action: "new" ) do %> Log in <span class="glyphicon glyphicon-cloud" aria-hidden="true"></span> <% end %></li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>
<% flash.each do |message_type, message| %>
    <div class="alert alert-warning" role="alert">
      <%= message %>
    </div>
<% end %>
</body>
</html>